#!/bin/sh

export TZ="UTC"
export POSTGRES_PORT="11162"
export POSTGRES_DB="buildlog"
export POSTGRES_USER="buildlog"
export POSTGRES_PASSWORD="buildlog_dev_password"
export DATABASE_URL="postgres://buildlog:buildlog_dev_password@127.0.0.1:11162/buildlog?sslmode=disable"
export GCS_EMULATOR_HOST="127.0.0.1:14443"
export STORAGE_EMULATOR_HOST="http://127.0.0.1:14443"
export GCS_BUCKET="buildlog-local"
export GCS_PUBLIC_BASE_URL="http://localhost:14443/download/storage/v1/b"
export GCP_PROJECT="buildlog-local"
export ADMIN_PASSWORD="111111"
export ADMIN_SESSION_SECRET="replace-with-a-long-random-secret"
