name: Deploy Production

on:
  push:
    branches:
      - main

# OIDC認証のためにIDトークンの発行権限を追加
permissions:
  contents: read
  id-token: write

jobs:
  deploy-api:
    name: Deploy Go API to Cloud Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/328735755994/locations/global/workloadIdentityPools/buildlog-pool/providers/github-provider'
          service_account: 'github-actions-deployer@buildlog-503612.iam.gserviceaccount.com'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy to Cloud Run (via Cloud Build)
        run: |
          cd api
          make deploy-prod
